---
# Source: eih-base-helm/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bb-web-eih-base-helm
  labels:
    helm.sh/chart: eih-base-helm-0.1.0
    app.kubernetes.io/name: eih-base-helm
    app.kubernetes.io/instance: bb-web
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: eih-base-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bb-web-eih-base-helm
  labels:
    helm.sh/chart: eih-base-helm-0.1.0
    app.kubernetes.io/name: eih-base-helm
    app.kubernetes.io/instance: bb-web
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: eih-base-helm
    app.kubernetes.io/instance: bb-web
---
# Source: eih-base-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-web-eih-base-helm
  labels:
    helm.sh/chart: eih-base-helm-0.1.0
    app.kubernetes.io/name: eih-base-helm
    app.kubernetes.io/instance: bb-web
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eih-base-helm
      app.kubernetes.io/instance: bb-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eih-base-helm
        app.kubernetes.io/instance: bb-web
    spec:
      serviceAccountName: bb-web-eih-base-helm
      securityContext:
        {}
      containers:
        - name: eih-base-helm
          securityContext:
            {}
          image: "us.icr.io/bb-web/bb-web:lts"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: eih-base-helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bb-web-eih-base-helm
  labels:
    helm.sh/chart: eih-base-helm-0.1.0
    app.kubernetes.io/name: eih-base-helm
    app.kubernetes.io/instance: bb-web
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "bazarbozorg.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: bb-web-eih-base-helm
              servicePort: 80
---
# Source: eih-base-helm/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "bb-web-eih-base-helm-test-connection"
  labels:
    helm.sh/chart: eih-base-helm-0.1.0
    app.kubernetes.io/name: eih-base-helm
    app.kubernetes.io/instance: bb-web
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['bb-web-eih-base-helm:80']
  restartPolicy: Never
